### PR TITLE
Feature/sg 3207 blip logging

### PR DESCRIPTION
**Pull request by tleyden**
Fixes https://github.com/couchbase/sync_gateway/issues/3207

### CODE REVIEW

**Comment by tleyden** [comment]
Example log file when running with:

```
    "log":[
        "Sync++"
    ],
```

* logMessage callback log entry: https://gist.github.com/tleyden/1c17bd8f9e9bf80668b2293afa253dd7#file-gistfile1-txt-L38

* logFrame callback log entry: https://gist.github.com/tleyden/1c17bd8f9e9bf80668b2293afa253dd7#file-gistfile1-txt-L47-L48

**Comment by tleyden** [comment]
> Use a callback w/ a SG log key when this logging is outputted (similar to what's already in place for BLIP level logging). Requires a blip enhancement.

From what I can tell, the current BLIP logging already called the pluggable callback function for all logging, even for message/frame level logging

> Ensure that setting BLIP++ in SG also enables BLIP+ and BLIP (similar to + handling for other keys)

This seemed to work out of the box

> Rename the SG log key as Sync/Sync+/Sync++

BLIP log keys renamed to Sync log keys everywhere.  

/cc @jamiltz -- does the BLIP log key need to be removed from docs after this change?

**Comment by tleyden** [comment]
TODO:

- Update go-blip to pass a log type enum (normal | logMessage | logFrame)

**Comment by jamiltz** [comment]
> @jamiltz -- does the BLIP log key need to be removed from docs after this change?

@tleyden no, we didn't document that key in the first place https://developer.couchbase.com/documentation/mobile/1.5/guides/sync-gateway/config-properties/index.html#1.5/logging-default-logKeys

**Comment by tleyden** [comment]
Ok thanks.  We should add Sync+ and Sync++, which are used to get verbose blip logging

**Comment by jamiltz** [comment]
Ok done https://github.com/couchbaselabs/couchbase-mobile-portal/commit/b7aa447c3f4a24a65c26e2ae1d083bd4efe1ece9

**Pull request merged**
